blueprint:
  name: Dynamic HVAC Room Manager Automation (Single Area)
  description: >
    Monitors presence, schedules, sleep status, and temperature to automatically set 
    HVAC modes and setpoints for a single specified area.
  domain: automation
  input:
    target_climate:
      name: Target climate
      description: The target climate
      selector:
        entity:
          domain: climate
    enable_guest:
      name: Enable Guest Mode
      description: Support guest mode for this.
      default: false
      selector:
        boolean: {}
    target_persons:
      name: Tracked Persons
      description: Select person entities to evaluate for presence and room schedules.
      selector:
        entity:
          domain: person
          multiple: true
    home_persons:
      name: Home Persons
      description: Select persons required to be home for active HVAC mode (if none are home, defaults to inactive).
      default: []
      selector:
        entity:
          domain: person
          multiple: true
    schedule_entities:
      name: Schedule Entities
      description: Entities that when true or on will result in the room being active. This includes the room and people within it.
      default: []
      selector:
        entity:
          multiple: true
    sleeping_sensors:
      name: Sleeping Sensors
      description: Select sleeping binary sensors or state entities that trigger HVAC recalculations.
      default: []
      selector:
        entity:
          multiple: true
    temp_sensor:
      name: Temperature Sensor
      description: Sensor used to monitor current ambient/outdoor temperature.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    hvac_mode_select:
      name: HVAC Mode Input Select
      description: The input select controlling the automation mode (Off, Auto, Guest, Away, Home).
      selector:
        entity:
          domain: input_select
    hot_weather_temp:
      name: Hot Weather Temperature Threshold
      description: Input number defining the threshold above which cooling is activated.
      selector:
        entity:
          domain: input_number
    cold_weather_temp:
      name: Cold Weather Temperature Threshold
      description: Input number defining the threshold below which heating is activated.
      selector:
        entity:
          domain: input_number
    default_heat_active_temp:
      name: Default Heat Active Temperature
      default: 68
      selector:
        number:
          min: 60
          max: 70
          step: 1
          unit_of_measurement: "°F" # or "°C"
          mode: slider              # Options: "slider" or "box"
    default_heat_inactive_temp:
      name: Default Heat Inactive Temperature
      default: 64
      selector:
        number:
          min: 60
          max: 70
          step: 1
          unit_of_measurement: "°F" # or "°C"
          mode: slider              # Options: "slider" or "box"
    default_heat_sleep_temp:
      name: Default Heat Sleeping Temperature
      default: 66
      selector:
        number:
          min: 60
          max: 70
          step: 1
          unit_of_measurement: "°F" # or "°C"
          mode: slider              # Options: "slider" or "box"
    default_cool_active_temp:
      name: Default cool active Temperature
      default: 76
      selector:
        number:
          min: 70
          max: 80
          step: 1
          unit_of_measurement: "°F" # or "°C"
          mode: slider              # Options: "slider" or "box"
    default_cool_inactive_temp:
      name: Default Cool Inactive Temperature
      default: 80
      selector:
        number:
          min: 70
          max: 80
          step: 1
          unit_of_measurement: "°F" # or "°C"
          mode: slider              # Options: "slider" or "box"
    default_cool_sleep_temp:
      name: Default Cool Sleeping Temperature
      default: 78
      selector:
        number:
          min: 70
          max: 80
          step: 1
          unit_of_measurement: "°F" # or "°C"
          mode: slider              # Options: "slider" or "box"
mode: queued
max: 10

triggers:
  - trigger: state
    entity_id: !input hvac_mode_select
    for:
      seconds: 50
  - trigger: state
    entity_id: !input home_persons
    for:
      seconds: 50
  - trigger: state
    entity_id: !input schedule_entities
    for:
      seconds: 50
  - trigger: state
    entity_id: !input sleeping_sensors
    for:
      seconds: 50
  - trigger: time_pattern
    hours: "*"
    minutes: "00"
    seconds: "00"

conditions:
  - alias: "Prevent running more than once every 30 seconds"
    condition: template
    value_template: >-
      {{ this.attributes.last_triggered is none or 
         (as_timestamp(now()) - as_timestamp(this.attributes.last_triggered)) > 30 }}

actions:
  - variables:
      is_guest_supported: !input enable_guest
      temp_sensor: !input temp_sensor
      hvac_mode_select: !input hvac_mode_select
      hot_weather_temp: !input hot_weather_temp
      cold_weather_temp: !input cold_weather_temp
      target_persons: !input target_persons
      home_persons: !input home_persons
      target_climate: !input target_climate
      active_entities: !input schedule_entities

      current_temp: "{{ states(temp_sensor) }}"
      people_home: >
        {{ home_persons | select('is_state', 'home') | list }}
      people_in_room: >
        {{ target_persons | select('is_state', 'home') | list }}
      is_active: >-
        {{ active_entities | map('states') | max == 'on' }}
      is_sleep: >-
        {{ sleeping_sensors | map('states') | max == 'on' }}
      hvac_active_heat: !input default_heat_active_temp
      hvac_inactive_heat: !input default_heat_inactive_temp
      hvac_sleep_heat: !input default_heat_sleep_temp
      hvac_active_cool: !input default_cool_active_temp
      hvac_inactive_cool: !input default_cool_inactive_temp
      hvac_sleep_cool: !input default_cool_sleep_temp

  - if:
      - condition: template
        value_template: >-
          {{ target_climate is defined and target_climate != '' and 
             is_guest_supported and states(hvac_mode_select) != 'Guest' }}
    then:
      - choose:
          # --- OFF MODE ---
          - conditions:
              - condition: state
                entity_id: !input hvac_mode_select
                state: "Off"
            sequence:
              - action: climate.set_hvac_mode
                target:
                  entity_id: "{{ target_climate }}"
                data:
                  hvac_mode: "off"
                alias: Turn off
            alias: "Off"

          # --- SLEEP MODE ---
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input hvac_mode_select
                    state: Auto
                  - condition: state
                    entity_id: !input hvac_mode_select
                    state: Guest
                alias: HVAC Guest or Auto
              - alias: If anyone sleeping
                condition: template
                value_template: "{{ is_sleep }}"
            sequence:
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        above: !input hot_weather_temp
                    sequence:
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          temperature: "{{ hvac_sleep_cool }}"
                          hvac_mode: cool
                        alias: Cool to desired sleep
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        above: !input cold_weather_temp
                    sequence:
                      - action: climate.set_hvac_mode
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: "off"
                        enabled: false
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: auto
                          temperature: 72
                        alias: Auto 72
                        enabled: false
                      - action: climate.set_hvac_mode
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: fan_only
                        enabled: true
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        below: !input cold_weather_temp
                    sequence:
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          temperature: "{{ hvac_sleep_heat }}"
                          hvac_mode: heat
                        alias: Heat to desired sleep
                enabled: true
              - action: climate.set_fan_mode
                target:
                  entity_id: "{{ target_climate }}"
                data:
                  fan_mode: auto
            alias: Sleep

          # --- INACTIVE MODE ---
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input hvac_mode_select
                    state: Away
                  - condition: and
                    conditions:
                      - condition: or
                        conditions:
                          - condition: state
                            entity_id: !input hvac_mode_select
                            state: Auto
                          - condition: state
                            entity_id: !input hvac_mode_select
                            state: Guest
                      - condition: or
                        conditions:
                          - alias: If no required adults home
                            condition: template
                            value_template: "{{ people_home | length == 0 }}"
                          - alias: If inactive
                            condition: template
                            value_template: "{{ not is_active }}"
            sequence:
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        above: !input hot_weather_temp
                    sequence:
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          temperature: "{{ hvac_inactive_cool }}"
                          hvac_mode: cool
                        alias: Cool to desired inactive
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        above: !input cold_weather_temp
                    sequence:
                      - action: climate.set_hvac_mode
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: fan_only
                        enabled: false
                      - action: climate.set_hvac_mode
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: "off"
                        enabled: true
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: auto
                          temperature: 72
                        alias: Auto 72
                        enabled: false
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        below: !input cold_weather_temp
                    sequence:
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          temperature: "{{ hvac_inactive_heat }}"
                          hvac_mode: heat
                        alias: Heat to desired inactive
                enabled: true
              - action: climate.set_fan_mode
                target:
                  entity_id: "{{ target_climate }}"
                data:
                  fan_mode: auto
                enabled: true
            alias: Inactive

          # --- ACTIVE MODE ---
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: !input hvac_mode_select
                    state: Home
                  - condition: and
                    conditions:
                      - condition: or
                        conditions:
                          - condition: state
                            entity_id: !input hvac_mode_select
                            state: Auto
                          - condition: state
                            entity_id: !input hvac_mode_select
                            state: Guest
                      - alias: If anyone home
                        condition: template
                        value_template: "{{ people_home | length > 0 }}"
                      - alias: If is active
                        condition: template
                        value_template: "{{ is_active }}"
            sequence:
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        above: !input hot_weather_temp
                    sequence:
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          temperature: "{{ hvac_active_cool }}"
                          hvac_mode: cool
                        alias: Cool to preferred active
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        above: !input cold_weather_temp
                    sequence:
                      - action: climate.set_hvac_mode
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: "off"
                        enabled: true
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          hvac_mode: auto
                          temperature: 72
                        alias: Auto 72
                        enabled: false
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input temp_sensor
                        below: !input cold_weather_temp
                    sequence:
                      - action: climate.set_temperature
                        target:
                          entity_id: "{{ target_climate }}"
                        data:
                          temperature: "{{ hvac_active_heat }}"
                          hvac_mode: heat
                        alias: Heat to preferred active
                enabled: true
              - action: climate.set_fan_mode
                target:
                  entity_id: "{{ target_climate }}"
                data:
                  fan_mode: auto
                enabled: true
            alias: Active
        enabled: true
